name: Build Flutter AAB & APK (Optimized)

on:
  push:
    branches:
      - main # Auslösen bei Push auf main
  workflow_dispatch: # Manuelles Starten erlaubt

jobs:
  build:
    name: Build Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
            ${{ env.HOME }}/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Read version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build AppBundle (.aab)
        run: flutter build appbundle --release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: travelmate-v${{ steps.version.outputs.version }}-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Build APK (.apk)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: travelmate-v${{ steps.version.outputs.version }}-apk
          path: build/app/outputs/flutter-apk/app-release.apk
